# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # Servicios propios
    file.utils:
        class: AppBundle\Services\FileUtils
        arguments: ['@logger', '@doctrine.orm.entity_manager']

    # Listeners
    listener.kernel.error:
        class: AppBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
            
    listener.doctrine.albumCreation:
        class: AppBundle\EventListener\AlbumCreation
        tags:
            - { name: doctrine.event_listener, event: postPersist }            